base:
  project: fashionapparel-project
  target_col: label

data_source:
  s3_source_train: data_given/fashion-mnist_train.csv
  s3_source_test: data_given/fashion-mnist_test.csv

load_data:
  raw_train_dataset_csv: data/raw/fashion-mnist_train.csv
  raw_test_dataset_csv: data/raw/fashion-mnist_test.csv

split_data:
  train_path: data/processed/fashion-mnist_train.csv
  test_path: data/processed/fashion-mnist_test.csv


estimators:
  CnnNetwork:
    params:
      loss: "sparse_categorical_crossentropy"
      optimiser: "adam"
      metrics: ['accuracy']
      activation: "softmax"
      batch_size: 64
      epochs: 2
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/full_mnist_model.h5

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: CNN Experiment
  run_name: mlops
  registered_model_name: FashionMnistModel
  remote_server_uri: http://0.0.0.0:1234